---
title: "biostat203bhw4"
format: html
editor: visual
author: Yasmine Tani; UID 406579988
---

# Biostatistics 203B - Homework 4

```{r}
sessionInfo()
```

```{r}
memuse::Sys.meminfo()
```

```{r}
library(bigrquery)
library(dbplyr)
library(DBI)
library(gt)
library(gtsummary)
library(tidyverse)
```

## **Q1. Compile the ICU cohort in HW3 from the Google BigQuery database**

### **Q1.1 Connect to BigQuery**

```{r}
# path to the service account token
satoken <- "biostat-203b-2026-winter-92fefbfab477.json"
# BigQuery authentication using service account
bq_auth(path = satoken)
```

```{r}
# connect to the BigQuery database `biostat-203b-2025-mimiciv_3_1`
con_bq <- dbConnect(
  bigrquery::bigquery(),
  project = "biostat-203b-2025-winter",
  dataset = "mimiciv_3_1",
  billing = "biostat-203b-2025-winter"
)
con_bq
```

```{r}
dbListTables(con_bq)
```

### **Q1.2 ICU Stays Data**

```{r}
# full ICU stays table
icustays_tble <- tbl(con_bq, "icustays") |>
  arrange(subject_id, hadm_id, stay_id) |>
  # show_query() |>
  print(width = Inf)
```

### **Q1.3 Admissions Data**

```{r}
admissions_tble <- tbl(con_bq, "admissions") |>
  arrange(subject_id, hadm_id) |>
  # show_query() |>
  print(width = Inf)
```

### **Q1.4 Patients Data**

```{r}
patients_tble <- tbl(con_bq, "patients") |>
  arrange(subject_id) |>
  print(width = Inf)
```

### **Q1.5 LabEvents Data**

```{r}
labevents_tble <- tbl(con_bq, "labevents") %>%
  # hw3 labs that we want
  filter(itemid %in% c(50912, 50971, 50983, 50902, 50882, 51221, 51301, 50931)) %>%
  # keep only subjects in icustays_tble
  semi_join(icustays_tble, by = "subject_id") %>%
  # join with icustays to get the intime
  left_join(
    icustays_tble %>% select(subject_id, stay_id, intime),
    by = "subject_id"
  ) %>%
  # labs taken BEFORE ICU admission
  filter(storetime <= intime) %>%
  # very last measurement
  group_by(subject_id, stay_id, itemid) %>%
  slice_max(order_by = storetime, n = 1) %>%
  ungroup() %>%
  select(subject_id, stay_id, itemid, valuenum) %>%
  # change itemid codes into column names
  pivot_wider(names_from = itemid, values_from = valuenum) %>%
  # making IDs the atcul lab names
  rename(
    creatinine = `50912`,
    potassium = `50971`,
    sodium = `50983`,
    chloride = `50902`,
    bicarbonate = `50882`,
    hematocrit = `51221`,
    wbc = `51301`,
    glucose = `50931`
  ) %>%
  arrange(subject_id, stay_id) %>%
  collect()
```

```{r}
# antoinette advised we check space to ensure we did properly
nrow(labevents_tble)

head(labevents_tble)
```

### **Q1.6 chartevents data**

```{r}
chartevents_tble <- tbl(con_bq, "chartevents") |>
  filter(itemid %in% c(220045, 220179, 220180, 220210, 223761)) |>
  semi_join(icustays_tble, by = "subject_id") |>
  left_join(
    icustays_tble |> select(subject_id, stay_id, intime, outtime),
    by = c("subject_id", "stay_id")
  ) |>
  filter(charttime >= intime & charttime <= outtime) |>
  group_by(subject_id, stay_id, itemid) |>
  filter(charttime == min(charttime, na.rm = TRUE)) |>
  summarize(
    valuenum = mean(valuenum, na.rm = TRUE), 
    .groups = "drop"
  ) |>
  pivot_wider(names_from = itemid, values_from = valuenum) |>
  rename(
    heart_rate  = `220045`,
    sys_bp      = `220179`,
    dias_bp     = `220180`,
    resp_rate   = `220210`,
    temp_f      = `223761`
  ) |>
  collect()
```

```{r}
nrow(chartevents_tble)
```

### **Q1.7 Putting Things Together** 

```{r}
mimic_icu_cohort <- icustays_tble |>
  #merging
  left_join(admissions_tble, by = c("subject_id", "hadm_id")) |>
  left_join(patients_tble, by = "subject_id") |>

  collect() |>
  # adults only age calculation like b4 (tho i think boston is only adults but)
  mutate(age = year(intime) - (anchor_year - anchor_age)) |>
  filter(age >= 18) |>
  # merge w labevents and chartevents tables
  left_join(labevents_tble, by = c("subject_id", "stay_id")) |>
  left_join(chartevents_tble, by = c("subject_id", "stay_id")) |>

  arrange(subject_id, hadm_id, stay_id) |>
  print(width = Inf)
```

### **Q1.8 Preprocessing**

```{r}
library(forcats)
library(gtsummary)

mimic_icu_cohort <- mimic_icu_cohort |>
  # lump infrequent levels into other 
  mutate(across(
    c(first_careunit, last_careunit, admission_type, 
      admission_location, discharge_location),
    ~ fct_lump_n(.x, n = 4, other_level = "Other")
  )) |>
  # collapse race into 5 levels
  mutate(race = fct_collapse(race,
    WHITE    = grep("WHITE", levels(as.factor(race)), value = TRUE),
    BLACK    = grep("BLACK", levels(as.factor(race)), value = TRUE),
    HISPANIC = grep("HISPANIC", levels(as.factor(race)), value = TRUE),
    ASIAN    = grep("ASIAN", levels(as.factor(race)), value = TRUE),
    other_level = "Other"
  )) |>
  # create los_long variable
  mutate(los_long = los >= 2) |>
  # tbl_summary stratified by los_long
  select(los_long, first_careunit, last_careunit, admission_type, race, age, gender)

mimic_icu_cohort |>
  tbl_summary(by = los_long) |>
  add_p() # add p-values to see if groups differ
```

### 

### **Q1.9 Save the final tibble**

```{r}
# make a directory mimiciv_shiny
if (!dir.exists("mimiciv_shiny")) {
  dir.create("mimiciv_shiny")
}
# save the final tibble
if (exists("mimic_icu_cohort")) {
  mimic_icu_cohort |>
    write_rds("mimiciv_shiny/mimic_icu_cohort.rds", compress = "gz")
}
```

```{r}
if (exists("con_bq")) {
  dbDisconnect(con_bq)
}
rm(list = ls())
```
